spring:
  cloud:
    gateway:
      server:
          webmvc:
            routes:
            - id: ms-company
              uri: lb://ms-company
              predicates:
              - path=/api/company/**
              filters:
              - StripPrefix=2
            - id: ms-documents
              uri: lb://ms-documents
              predicates:
              - path=/api/documents/**
              filters:
              - StripPrefix=2
            - id: ms-user
              uri: lb://ms-user
              predicates:
              - path=/api/user/**
              filters:
              - StripPrefix=2
            - id: ms-transactions
              uri: lb://ms-transactions
              predicates:
              - path=/api/transactions/**
              filters:
              - StripPrefix=2