spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-company
              uri: lb://ms-company
              predicates:
              - path=/api/ms-company/**
              filters:
              - StripPrefix=2
            - id: ms-documents
              uri: lb://ms-documents
              predicates:
              - path=/api/ms-documents/**
              filters:
              - StripPrefix=2
            - id: ms-user
              uri: lb://ms-user
              predicates:
              - path=/api/ms-user/**
              filters:
              - StripPrefix=2